### PR TITLE
Add called variants to pipeline result

### PR DESCRIPTION
**Pull request by mhkc**
This PR adds support to include variants called with delly and freebayes to a sample.

### CODE REVIEW

**Review by ryanjameskennedy — APPROVED** [review]
LGTM!

**Review by ryanjameskennedy — CHANGES_REQUESTED** [review]
Resolve conflict please sir

**Review by ryanjameskennedy — CHANGES_REQUESTED** [review]
Linting failed as it was below 9 (8.87)

**Comment by mhkc** [comment]
> Linting failed as it was below 9 (8.87)

Well fix that later.

**Pull request merged**
